In [82]:
import numpy as np
import torch

a = torch.ones([3,3])

a.size()
print(a)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [83]:
f = torch.mean(a, dim = 1, keepdim=True)
f

tensor([[1.],
        [1.],
        [1.]])

In [70]:
b = torch.split(a,1, dim=1)

b


(tensor([[1.],
         [1.],
         [1.]]),
 tensor([[1.],
         [1.],
         [1.]]),
 tensor([[1.],
         [1.],
         [1.]]))

In [71]:
for i in b:
    print(i)

tensor([[1.],
        [1.],
        [1.]])
tensor([[1.],
        [1.],
        [1.]])
tensor([[1.],
        [1.],
        [1.]])


In [72]:
a = [1,2]
c = []
for i in a:
    c.append(b[i]) 



AttributeError: 'list' object has no attribute 'size'

In [ ]:
d = torch.cat(c, 1)
d.size()

torch.Size([3, 2])

In [ ]:
d

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])